/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Song } from "./Song";
import { SongCountArgs } from "./SongCountArgs";
import { SongFindManyArgs } from "./SongFindManyArgs";
import { SongFindUniqueArgs } from "./SongFindUniqueArgs";
import { CreateSongArgs } from "./CreateSongArgs";
import { UpdateSongArgs } from "./UpdateSongArgs";
import { DeleteSongArgs } from "./DeleteSongArgs";
import { Album } from "../../album/base/Album";
import { SongService } from "../song.service";
@graphql.Resolver(() => Song)
export class SongResolverBase {
  constructor(protected readonly service: SongService) {}

  async _songsMeta(
    @graphql.Args() args: SongCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Song])
  async songs(@graphql.Args() args: SongFindManyArgs): Promise<Song[]> {
    return this.service.songs(args);
  }

  @graphql.Query(() => Song, { nullable: true })
  async song(@graphql.Args() args: SongFindUniqueArgs): Promise<Song | null> {
    const result = await this.service.song(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Song)
  async createSong(@graphql.Args() args: CreateSongArgs): Promise<Song> {
    return await this.service.createSong({
      ...args,
      data: {
        ...args.data,

        album: args.data.album
          ? {
              connect: args.data.album,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Song)
  async updateSong(@graphql.Args() args: UpdateSongArgs): Promise<Song | null> {
    try {
      return await this.service.updateSong({
        ...args,
        data: {
          ...args.data,

          album: args.data.album
            ? {
                connect: args.data.album,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Song)
  async deleteSong(@graphql.Args() args: DeleteSongArgs): Promise<Song | null> {
    try {
      return await this.service.deleteSong(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Album, {
    nullable: true,
    name: "album",
  })
  async getAlbum(@graphql.Parent() parent: Song): Promise<Album | null> {
    const result = await this.service.getAlbum(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
